### ISSUE TITLE
Dropdown not closing other dropdowns

### ISSUE THREAD

**Issue by 57even** [ianmartorell/meteor-accounts-ui-bootstrap-3#136] opened 2015-06-29 11:12 UTC
If I also have a dropdown next to the `meteor-accounts-ui-bootstrap-3` dropdown, it causes problems when I have the other dropdown active and then clicks the `meteor-accounts-ui-bootstrap-3` dropdown since the other dropdown wont close.

![dropdown](https://cloud.githubusercontent.com/assets/4533204/8406808/7d9070a8-1e60-11e5-9642-4e21f36007dc.png)

**Comment by ianmartorell** [comment] 2015-07-13 12:13
It sounds to me like the problem is with your other dropdown. Does the opposite (having this package's dropdown open and clicking on the other one) work well?

**Comment by daoli** [comment] 2015-07-15 19:58
I had the same problem. Removing these lines in ``login_buttons_dropdown.js`` resolves the issue.

```
-               },
-               'click .dropdown-toggle': function(event) {
-                       event.stopPropagation();
-                       Template._loginButtons.toggleDropdown();
```

**Comment by ianmartorell** [comment] 2015-07-16 17:35
You're right, that was in place from when I tried to fix #147. This will be fixed in 1.2.74 when I publish in a few minutes

**Closed** 2015-07-16 17:36 UTC
